name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at 9:30AM IST
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Project
        run: |
          curl -X GET "https://vobkfalflhihxfmaezo.supabase.co/rest/v1/user_wallets" \
          -H "apikey: ${{ secrets.SUPABASE_API_KEY }}"
